const { withSettingsGradle } = require('expo/config-plugins');

const MARKER = '// @generated by withAndroidAutolinkingCacheGuard';
const SNIPPET = `${MARKER}
def reactNativeProjectRoot = rootDir.parentFile
def workspaceRoot = reactNativeProjectRoot.parentFile
def pnpmLockPath = new File(workspaceRoot, "pnpm-workspace.yaml").isFile() ? "../pnpm-lock.yaml" : "pnpm-lock.yaml"
def autolinkingLockFiles = layout.rootDirectory.dir("../").files(
  "yarn.lock",
  "package-lock.json",
  "package.json",
  "react-native.config.js",
  pnpmLockPath,
  "../pnpm-workspace.yaml"
)

def invalidateStaleAutolinkingCache = {
  def autolinkingJson = new File(rootDir, "build/generated/autolinking/autolinking.json")
  if (!autolinkingJson.isFile() || autolinkingJson.length() == 0L) {
    return
  }

  try {
    def config = new groovy.json.JsonSlurper().parse(autolinkingJson)
    def reactNativePath = config.reactNativePath
    def missingAndroidProject = config.dependencies?.values()?.find { dependency ->
      def android = dependency.platforms?.android
      def sourceDir = android?.sourceDir
      return sourceDir != null &&
        android?.isPureCxxDependency != true &&
        !new File(sourceDir.toString()).isDirectory()
    }
    def staleReason = null
    if (reactNativePath != null && !new File(reactNativePath.toString()).isDirectory()) {
      staleReason = "missing reactNativePath"
    } else if (missingAndroidProject != null) {
      staleReason = "missing \${missingAndroidProject.name} Android sourceDir"
    }

    if (staleReason != null) {
      println("[Autolinking] Removed stale Android autolinking cache (\${staleReason}); it will be regenerated.")
      autolinkingJson.delete()
    }
  } catch (Exception ignored) {
    println("[Autolinking] Removed invalid Android autolinking cache; it will be regenerated.")
    autolinkingJson.delete()
  }
}

invalidateStaleAutolinkingCache()
`;

const COMMUNITY_AUTOLINKING_CALL = `ex.autolinkLibrariesFromCommand(
      ["npx", "@react-native-community/cli", "config"],
      reactNativeProjectRoot,
      autolinkingLockFiles
    )`;

const EXPO_AUTOLINKING_CALL = `ex.autolinkLibrariesFromCommand(
      expoAutolinking.rnConfigCommand,
      reactNativeProjectRoot,
      autolinkingLockFiles
    )`;

function addAutolinkingCacheGuard(contents) {
  let next = contents;
  const anchor = 'extensions.configure(com.facebook.react.ReactSettingsExtension) { ex ->';

  if (!next.includes(MARKER)) {
    if (next.includes(anchor)) {
      next = next.replace(anchor, `${SNIPPET}\n${anchor}`);
    } else {
      next = `${next.trimEnd()}\n\n${SNIPPET}\n`;
    }
  }

  next = next.replace('ex.autolinkLibrariesFromCommand()', COMMUNITY_AUTOLINKING_CALL);
  next = next.replace(
    'ex.autolinkLibrariesFromCommand(expoAutolinking.rnConfigCommand)',
    EXPO_AUTOLINKING_CALL
  );

  return next;
}

module.exports = function withAndroidAutolinkingCacheGuard(config) {
  return withSettingsGradle(config, (config) => {
    if (config.modResults.language === 'groovy') {
      config.modResults.contents = addAutolinkingCacheGuard(config.modResults.contents);
    }

    return config;
  });
};

module.exports.addAutolinkingCacheGuard = addAutolinkingCacheGuard;
