const { withProjectBuildGradle } = require('expo/config-plugins');

const MARKER = '// @generated by withAndroidNdkVersionForSubprojects';
const SNIPPET = `${MARKER}
subprojects { subproject ->
  subproject.plugins.withId("com.android.application") {
    if (rootProject.ext.has("ndkVersion")) {
      subproject.android.ndkVersion rootProject.ext.ndkVersion
    }
  }
  subproject.plugins.withId("com.android.library") {
    if (rootProject.ext.has("ndkVersion")) {
      subproject.android.ndkVersion rootProject.ext.ndkVersion
    }
  }
}
`;

function addNdkVersionSnippet(contents) {
  if (contents.includes(MARKER)) {
    return contents;
  }

  const anchor = 'apply plugin: "com.facebook.react.rootproject"';
  if (contents.includes(anchor)) {
    return contents.replace(anchor, `${anchor}\n\n${SNIPPET}`);
  }

  return `${contents.trimEnd()}\n\n${SNIPPET}\n`;
}

module.exports = function withAndroidNdkVersionForSubprojects(config) {
  return withProjectBuildGradle(config, (config) => {
    if (config.modResults.language === 'groovy') {
      config.modResults.contents = addNdkVersionSnippet(config.modResults.contents);
    }

    return config;
  });
};
