import type { AppLineIconName } from '../../visual/AppLineIcon';

export const appIconRegistry = {
  menu: true,
  search: true,
  add: true,
  'chat-add': true,
  chat: true,
  apps: true,
  drive: true,
  user: true,
  back: true,
  history: true,
  refresh: true,
  spark: true,
  brain: true,
  'plan-mode': true,
  'plan-mode-active': true,
  question: true,
  steer: true,
  pin: true,
  check: true,
  'arrow-up': true,
  'arrow-down': true,
  stop: true,
  play: true,
  image: true,
  'chevron-up': true,
  'chevron-down': true,
  close: true,
  copy: true,
  file: true,
  tool: true,
  'wrap-text': true,
  moon: true,
} as const satisfies Record<AppLineIconName, true>;

export type AppIconGlyphName = keyof typeof appIconRegistry;
